// ⚠️ FILE GENERATO — non modificare a mano.
// Prodotto da scripts/gen-report-content.mjs a partire da
// contenuti-report-5-elementi.md (fonte editoriale unica, Federica/Elena).
// Rigenerare con: node scripts/gen-report-content.mjs
//
// Contiene SOLO i blocchi "TESTO PER LA TITOLARE" (mai le NOTE INTERNE, mai i
// nomi degli elementi nel testo). Usato da lib/beautyx/reportContent per
// l'assemblaggio deterministico del report (task #153).

export const REPORT_CONTENT = {
  "apertura": {
    "fuoco": {
      "base": "Hai appena raccontato pezzi veri della tua giornata da titolare — non hai risposto a caselle, hai raccontato quello che fai davvero. E da come lo fai, un tratto emerge più forte di tutti gli altri: sei tu, tra tutte le persone che potresti essere, quella che non aspetta. Quando c'è da decidere, decidi lì, sul momento, con la cliente davanti o il telefono già in mano. Questo non è tutto quello che sei — dentro di te c'è anche chi ascolta con calma, chi rimette in discussione un sistema intero, chi tiene tutto fermo con pazienza, chi controlla il dettaglio fino in fondo: sono tutte parti tue, solo che oggi una parla più forte delle altre. Nelle prossime pagine trovi il ritratto completo di quello che hai raccontato, e il punto preciso in cui questa energia, oggi, potrebbe scorrere ancora meglio.",
      "differenzaAmbito": "E c'è un ambito preciso, tra clienti, staff e conti, dove questa spinta si sente ancora di più che negli altri due."
    },
    "acqua": {
      "base": "Hai appena raccontato pezzi veri della tua giornata da titolare — non hai risposto a caselle, hai raccontato quello che fai davvero. E da come lo fai, un tratto emerge più forte di tutti gli altri: sei tu, tra tutte le persone che potresti essere, quella che si ferma prima di giudicare. Prima di decidere fai una domanda, cerchi cosa c'è sotto quello che vedi in superficie — con una cliente, con lo staff, con i conti. Questo non è tutto quello che sei — dentro di te c'è anche chi agisce d'istinto, chi rimette in discussione un sistema intero, chi tiene tutto fermo con pazienza, chi controlla il dettaglio fino in fondo: sono tutte parti tue, solo che oggi una parla più forte delle altre. Nelle prossime pagine trovi il ritratto completo di quello che hai raccontato, e il punto preciso in cui questa capacità, oggi, potrebbe portarti ancora più lontano.",
      "differenzaAmbito": "E c'è un ambito preciso, tra clienti, staff e conti, dove questa capacità si sente ancora di più che negli altri due."
    },
    "aria": {
      "base": "Hai appena raccontato pezzi veri della tua giornata da titolare — non hai risposto a caselle, hai raccontato quello che fai davvero. E da come lo fai, un tratto emerge più forte di tutti gli altri: sei tu, tra tutte le persone che potresti essere, quella che davanti a un imprevisto non pensa solo a quel caso — pensa a tutto il sistema che c'è dietro, una procedura, un listino, un modo di lavorare che riguarda tutti. Questo non è tutto quello che sei — dentro di te c'è anche chi agisce d'istinto, chi ascolta con calma prima di muoversi, chi tiene tutto fermo con pazienza, chi controlla il dettaglio fino in fondo: sono tutte parti tue, solo che oggi una parla più forte delle altre. Nelle prossime pagine trovi il ritratto completo di quello che hai raccontato, e il punto preciso in cui questa spinta, oggi, potrebbe portare frutti ancora più solidi.",
      "differenzaAmbito": "E c'è un ambito preciso, tra clienti, staff e conti, dove questa spinta a rivedere tutto si sente ancora di più che negli altri due."
    },
    "terra": {
      "base": "Hai appena raccontato pezzi veri della tua giornata da titolare — non hai risposto a caselle, hai raccontato quello che fai davvero. E da come lo fai, un tratto emerge più forte di tutti gli altri: sei tu, tra tutte le persone che potresti essere, quella che non si scompone. Un imprevisto arriva — una cliente che cambia idea, una collaboratrice che sbaglia, un mese sotto tono — e tu continui, con lo stesso passo e la stessa fiducia nel tempo. Questo non è tutto quello che sei — dentro di te c'è anche chi agisce d'istinto, chi ascolta con calma, chi rimette in discussione un sistema intero, chi controlla il dettaglio fino in fondo: sono tutte parti tue, solo che oggi una parla più forte delle altre. Nelle prossime pagine trovi il ritratto completo di quello che hai raccontato, e il punto preciso in cui questa solidità, oggi, potrebbe reggere ancora di più.",
      "differenzaAmbito": "E c'è un ambito preciso, tra clienti, staff e conti, dove questa stabilità si sente ancora di più che negli altri due."
    },
    "metallo": {
      "base": "Hai appena raccontato pezzi veri della tua giornata da titolare — non hai risposto a caselle, hai raccontato quello che fai davvero. E da come lo fai, un tratto emerge più forte di tutti gli altri: sei tu, tra tutte le persone che potresti essere, quella che non lascia scivolare niente. Controlli il dettaglio esatto — un orario, una cifra, una parola — anche quando agli altri sembrerebbe già abbastanza. Questo non è tutto quello che sei — dentro di te c'è anche chi agisce d'istinto, chi ascolta con calma, chi rimette in discussione un sistema intero, chi tiene tutto fermo con pazienza: sono tutte parti tue, solo che oggi una parla più forte delle altre. Nelle prossime pagine trovi il ritratto completo di quello che hai raccontato, e il punto preciso in cui questa precisione, oggi, potrebbe rendere ancora di più.",
      "differenzaAmbito": "E c'è un ambito preciso, tra clienti, staff e conti, dove questa cura del dettaglio si sente ancora di più che negli altri due."
    }
  },
  "ritratto": {
    "fuoco": {
      "eccesso_trasversale": "C'è un modo di essere titolare che si riconosce da come rispondi quando qualcosa non va per il verso giusto — con una cliente, con una collaboratrice, o davanti a una spesa che non avevi previsto. Tu non aspetti che la situazione si sistemi da sola: prendi il telefono e chiami, ti siedi subito con chi ha sbagliato, decidi la riparazione lo stesso pomeriggio. Quando un'idea ti accende, non la lasci raffreddare in un cassetto — la provi. Questa energia tiene il centro vivo anche nei giorni storti, ed è il motivo per cui chi lavora con te si affida a te proprio nei momenti critici. C'è però una costante che torna in quasi ogni episodio che racconti: la decisione arriva sempre nello stesso istante in cui nasce l'impulso, in ogni ambito, senza quasi mai un passaggio intermedio in cui ti fermi a chiederti cosa c'è sotto prima di muoverti. Come se, ogni volta, il tempo tra il sentire e il fare fosse sempre lo stesso — zero.",
      "eccesso_localizzato": "Con lo staff e con i conti non hai dubbi: se una collaboratrice sbaglia, la affronti subito; se un fornitore ti propone un affare scontato, decidi prima che scada l'offerta. Quella prontezza è la tua firma, in quei due mondi. Con le clienti, invece, il tuo passo cambia registro — lì rallenti, osservi, lasci che le cose si chiariscano con più calma. È una differenza che dice molto: significa che sai anche rallentare, quando la posta in gioco è la relazione con chi si siede sulla tua poltrona. Solo che, su personale e spese, quella stessa capacità resta ancora ferma fuori dalla porta.",
      "carenza_non_nutrita": "Raramente sei tu a muovere per prima le cose sul momento: aspetti, valuti, raccogli altri segnali prima di decidere — con una cliente che cambia idea, con una collaboratrice che propone qualcosa di nuovo, con un'occasione economica che si presenta all'improvviso. Non è indecisione, è un modo di procedere che ti appartiene. Ma quando ripensi ai momenti in cui avresti voluto sentire quello scatto — quella spinta a dire \"lo faccio adesso\" — noti che manca anche l'altra cosa: la sensazione di avere già un terreno abbastanza solido sotto i piedi da permetterti di rischiare. È come cercare la scintilla in un posto dove, al momento, non c'è ancora nemmeno la legna pronta."
    },
    "acqua": {
      "eccesso_trasversale": "C'è un modo di essere titolare che si vede in come reagisci quando qualcosa ti sorprende: una cliente che sparisce senza spiegazioni, una collaboratrice che sbaglia, un mese in cui il fatturato cala. Non rispondi a caldo — ti fermi, fai domande, cerchi di capire cosa c'è davvero dietro quello che vedi in superficie. Prima di giudicare un ritardo lo chiedi, prima di tagliare una spesa ti chiedi quanto userai davvero quel prodotto. Questa capacità di leggere sotto la superficie è merce rara in un settore dove si decide sempre di corsa. Se però ripensi alle ultime volte che hai capito qualcosa a fondo — cosa ne è rimasto, dopo? Nella maggior parte dei casi la comprensione resta legata a quella singola situazione, senza diventare qualcos'altro: una regola nuova, un modo diverso di lavorare che resti anche quando quella cliente, quella collaboratrice, quel mese sono già alle spalle.",
      "eccesso_localizzato": "Con le clienti e con i conti sei quella che si ferma, chiede, ascolta prima di muoversi — capisci sempre cosa c'è dietro un ritardo, dietro un calo di fatturato, prima di decidere. Con lo staff, invece, il tuo passo cambia: davanti a una collaboratrice che sbaglia o che ti chiede qualcosa, la tua prima reazione è più diretta, quasi immediata. In quei due mondi dove ti fermi ad ascoltare, però, la comprensione raramente arriva a diventare qualcosa che resta oltre il singolo episodio — una policy, un criterio nuovo, qualcosa di scritto che valga anche la prossima volta.",
      "carenza_non_nutrita": "Nella maggior parte degli episodi che racconti, il momento in cui ti fermi a chiedere \"cosa c'è davvero dietro\" arriva tardi, o non arriva — con una cliente che si lamenta, con una collaboratrice che sbaglia, con un conto che non torna, tendi ad agire o a decidere seguendo la prassi di sempre, più che a indagare. Eppure, quando ripensi a cosa ti servirebbe per fermarti davvero a capire, noti che manca anche un'altra cosa: l'abitudine a guardare i dettagli piccoli e precisi di una situazione — l'esatto passaggio in cui qualcosa si è inceppato, la cifra esatta, la frase esatta detta da chi ti sta davanti. Senza quel dettaglio in mano, la domanda \"cosa c'è dietro\" non ha quasi materiale su cui lavorare."
    },
    "aria": {
      "eccesso_trasversale": "Ogni imprevisto, per te, è anche una domanda più grande. Una recensione negativa non è solo da gestire: è l'occasione per rivedere il protocollo di quel trattamento per tutto il centro. Una collaboratrice che salta le procedure ti fa chiedere se le procedure vadano rese più chiare per tutte. Un mese di fatturato basso ti fa pensare se sia il momento di cambiare qualcosa di strutturale nel modo in cui organizzi il centro. Questo sguardo che va oltre il singolo episodio è quello che, nel tempo, fa evolvere davvero un centro invece di lasciarlo fermo agli stessi schemi da anni. Se però ripercorri gli ultimi cambiamenti che hai introdotto — uno dopo l'altro, in tutti e tre gli ambiti — noti che tra un ripensamento e il successivo passa sempre poco tempo. Come se il centro fosse sempre a metà di un cambiamento quando già ne arriva un altro.",
      "eccesso_localizzato": "Sul personale e sui conti sei quella che rimette in discussione tutto — procedure, criteri, organizzazione — appena vedi un segnale che qualcosa si potrebbe fare meglio. Con le clienti, invece, il tuo passo cambia: lì tendi a restare sul collaudato, quello che hai sempre fatto va bene così. In quei due mondi dove rivedi tutto, però, il ripensamento successivo arriva quasi sempre prima che il precedente abbia avuto il tempo di mostrare se ha funzionato davvero.",
      "carenza_non_nutrita": "Raramente sei tu a rimettere in discussione un sistema intero — un protocollo, un'organizzazione, un listino — anche quando qualcosa, nel singolo episodio, segnala che potrebbe non funzionare più come prima. Tendi a restare su quello che conosci, con una cliente che cambia idea come con una collaboratrice che propone qualcosa di nuovo. Quando ripensi a cosa ti servirebbe per sentire davvero l'urgenza di cambiare qualcosa di più grande, noti che manca anche un altro ingrediente: quella scintilla immediata, quell'energia che ti farebbe dire \"basta, lo cambio adesso\" invece di continuare a rimandare."
    },
    "terra": {
      "eccesso_trasversale": "C'è un modo di essere titolare che si riconosce da quanto poco, in fondo, ti scompone. Una cliente storica che se ne va senza dire niente, un fatturato che cala in bassa stagione, una collaboratrice che salta le procedure ma con le clienti va benissimo: tu non stravolgi nulla, continui a lavorare come hai sempre fatto, con la fiducia che il tempo e la coerenza pagano più di una reazione a caldo. Questa stabilità è quello che fa sentire il centro un posto sicuro, per chi ci lavora e per chi ci entra come cliente. Se però ripensi a quando è stata l'ultima volta che hai riguardato da vicino una di queste abitudini consolidate — lo spazio fisso lasciato a una cliente, il margine dato sempre alla stessa collaboratrice, il modo in cui affronti ogni bassa stagione — probabilmente fatica a venirti in mente. Restano ferme così come sono nate, senza che nessuno le riguardi mai da vicino.",
      "eccesso_localizzato": "Con le clienti e con lo staff sei un punto fermo: le stesse regole per tutte, lo stesso passo, la stessa fiducia nel tempo. Sui soldi, invece, il tuo passo cambia: davanti a un'occasione, uno sconto forte, un acquisto scontato in grande quantità, ti ritrovi a decidere di getto, spinta dall'entusiasmo del momento. Nei due mondi dove resti stabile, però, quella stessa stabilità non viene quasi mai riaperta e controllata nel dettaglio — resta un blocco unico, intoccato, anno dopo anno.",
      "carenza_non_nutrita": "Raramente qualcosa, nel tuo centro, resta uguale abbastanza a lungo da diventare \"il modo in cui si fa sempre\" — con le clienti, con lo staff, con i conti, ogni situazione tende a essere affrontata quasi da capo, più che appoggiandosi a una prassi già rodata. Quando ripensi a cosa ti servirebbe per lasciare che qualcosa si consolidi davvero, noti che manca anche un altro passaggio: il tempo che ti prendi, prima, per capire a fondo una situazione. Senza quella pausa di comprensione, ogni abitudine parte sempre un po' più fragile, prima ancora di avere la possibilità di mettere radici."
    },
    "metallo": {
      "eccesso_trasversale": "C'è un modo di essere titolare che si vede in quanto poco lasci scivolare: con una cliente controlli quale passaggio esatto del trattamento non ha retto, con una collaboratrice ricordi con precisione gli accordi presi, sui conti ricalcoli i margini reali prima di alzare un prezzo. Non ti accontenti del \"va bene così\" — vuoi sapere esattamente dove sta lo scarto tra quello che offri e lo standard che ti sei data. Questa cura del dettaglio è ciò che tiene alta la qualità percepita del centro, in ogni ambito. Se però ripensi a quante volte, di fronte a una decisione già abbastanza chiara, hai comunque scelto di controllare ancora un dettaglio prima di chiudere — probabilmente sono più di quante vorresti. Come se il momento in cui basta così, si decide e si va avanti, restasse sempre un passo più in là.",
      "eccesso_localizzato": "Con lo staff e con i conti sei precisa: standard chiari, criteri definiti, margini ricalcolati voce per voce. Con le clienti, invece, il tuo passo cambia — lì tendi più a restare su quello che hai sempre offerto, senza rimetterlo in discussione nel dettaglio. Nei due mondi dove sei più esigente, però, quella stessa precisione raramente sfocia in una decisione presa lì per lì, d'istinto: prima c'è sempre un altro giro di controllo.",
      "carenza_non_nutrita": "Capita che uno standard si abbassi un po' — un prodotto che non rende più come prima, un orario che scivola di qualche minuto, un prezzo che non copre più il margine di una volta — e che te ne accorga solo quando qualcuno te lo fa notare, non prima. Non è disattenzione: è che raramente ti fermi a controllare il singolo dettaglio finché tutto sembra reggere nell'insieme. Quando ripensi a cosa ti aiuterebbe a notare prima questi scarti, noti che manca anche un altro passaggio: la spinta a rivedere ogni tanto l'intero sistema — un'organizzazione, un listino, un protocollo — che è anche il momento in cui, naturalmente, i dettagli fuori posto vengono a galla da soli."
    }
  },
  "applicazione": {
    "fuoco": {
      "giaFluisce": "Non è un caso che le tue intuizioni più veloci siano spesso anche quelle che, con il tempo, aprono la strada a un ripensamento più grande: quando decidi di getto, qualcosa in te si accende anche per rimettere in discussione ciò che non va più bene. La tua energia, quando scorre, non si esaurisce nell'attimo in cui agisci — continua a lavorare anche dopo.",
      "domande": "Pensa all'ultima decisione presa di getto — con una cliente, una collaboratrice o una spesa. Se oggi tornassi a guardarla voce per voce, quale dettaglio preciso — un orario, una cifra, una frase esatta — scopriresti di non aver davvero verificato prima di dire \"faccio così\"? Quanto tempo, di solito, dedichi a controllare un particolare del genere prima che la decisione sia già presa? Se ti abituassi a fermarti su un solo dato concreto, sempre lo stesso tipo, un attimo prima di ogni scintilla d'azione — cosa pensi che cambierebbe in quello che capisci di ciò che hai deciso, dopo?"
    },
    "acqua": {
      "giaFluisce": "Non è un caso che le persone che ascolti con calma restino spesso le più fedeli al tuo centro nel tempo: capire davvero qualcuno — perché è in ritardo, perché ha sbagliato, perché ha rallentato — è già, di per sé, ciò che costruisce una fiducia che dura oltre il singolo episodio.",
      "domande": "Delle ultime tre volte che hai capito a fondo cosa c'era dietro un problema, quanto tempo è passato tra il momento in cui hai capito e il momento in cui hai fatto qualcosa di concreto con quella comprensione? C'è una di quelle volte in cui, invece di lasciarla lì a decantare, ti sei mossa subito, lo stesso giorno? Se la prossima comprensione importante la lasciassi accendere anche solo un piccolo gesto immediato, senza aspettare — quale sarebbe il primo che ti viene in mente?"
    },
    "aria": {
      "giaFluisce": "Ogni volta che ti fermi a chiederti perché una procedura non funziona più, o cosa sta cambiando nel centro, stai anche costruendo — per te e per chi lavora con te — una cura più fine di come sono fatte davvero le cose: le tue domande di sistema aprono già la strada a un livello di dettaglio che altrimenti resterebbe invisibile.",
      "domande": "L'ultimo cambiamento che hai messo in moto nel centro — un protocollo, un'organizzazione, un listino — quanto tempo ti sei presa, prima di deciderlo, per ascoltare davvero come lo avrebbe vissuto chi lo avrebbe applicato ogni giorno? Quando senti che qualcosa va rivisto da capo, cosa arriva prima: la comprensione piena di cosa non funziona, o già la spinta a cambiarlo? Se prima del prossimo ripensamento ti fermassi a chiedere, con calma, a chi lavora con te o a una cliente cosa vede lei che tu non vedi ancora — cosa pensi che scopriresti?"
    },
    "terra": {
      "giaFluisce": "La solidità che costruisci ogni giorno è anche quello che, quando arriva il momento di decidere in fretta qualcosa di importante, ti permette di farlo senza sentire il terreno tremare sotto i piedi: la tua base ferma è ciò che rende possibili, e sicuri, anche gli scatti più immediati.",
      "domande": "Da quanto tempo un'abitudine del centro — uno spazio fisso lasciato a una cliente, un margine sempre dato alla stessa persona, il modo in cui affronti ogni bassa stagione — non viene ripensata da capo nell'intera logica che c'è dietro, non solo controllata nel singolo dettaglio? Se ti chiedessi se l'intera organizzazione dietro quella prassi meriti ancora di restare così com'è, cosa pensi che scopriresti a monte? Cosa ti trattiene di solito dal mettere in discussione non il singolo passaggio, ma il sistema intero che lo regge?"
    },
    "metallo": {
      "giaFluisce": "La cura che metti in ogni dettaglio è anche ciò che permette a chi ti sta vicino — una cliente, una collaboratrice — di sentirsi presa sul serio: capire che qualcuno ha controllato proprio quel passaggio, quella cifra, quella parola, comunica un'attenzione che nessun discorso generico potrebbe dare.",
      "domande": "L'ultima volta che hai rimandato una decisione per controllare ancora un dettaglio, quanto ti saresti sentita sicura a deciderla comunque, contando solo sulla solidità di ciò che nel centro hai già costruito nel tempo? C'è una base, un'abitudine, un rapporto così consolidato che, a pensarci bene, potrebbe reggere anche una scelta presa d'istinto, senza un altro passaggio di verifica? Cosa cambierebbe se ti fidassi un po' di più di quella stabilità, prima di rimandare ancora?"
    }
  },
  "fraseMotivazionale": {
    "fuoco": "La scintilla che hai oggi è già abbastanza per accendere il prossimo passo.",
    "acqua": "Capire davvero qualcuno, anche solo per un istante, è già un modo di cambiare le cose.",
    "aria": "Lo stesso soffio che rimette in discussione le cose vecchie è quello che apre la strada a quelle nuove.",
    "terra": "Ogni giorno che resti ferma nel modo giusto, stai costruendo qualcosa che durerà molto più di oggi.",
    "metallo": "Il dettaglio che curi quando nessuno guarda è quello che si nota di più quando qualcuno guarda."
  },
  "ctaFinale": "Hai appena visto, forse per la prima volta scritto nero su bianco, come funzioni davvero tu quando guidi il tuo centro — cosa ti fa scattare, cosa tieni fermo, dove la tua energia scorre libera e dove invece si blocca. È lo sguardo che di solito riservi sempre agli altri: alle clienti che ascolti, allo staff che guidi, ai conti che tieni in ordine. Oggi, per una volta, quello sguardo è tornato su di te.\n\nGuardarsi da sole è già un passo importante — ed è anche solo l'inizio. Chi passa le giornate a prendersi cura di tutti gli altri merita, prima o poi, di trovare qualcuno che faccia lo stesso con lei.\n\nIl passo successivo ha già un nome — CARE — pensato apposta per questo: continuare insieme, con un confronto vero, guidato da una persona in carne e ossa che parte proprio dal tuo profilo, quello che queste pagine hanno solo iniziato a mostrare. Se ti va di andare oltre questo report, quel confronto ti aspetta."
}
